apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-repo
  description: The place to be, for great artists
  labels:
    example.com/custom: custom_label_value
  annotations:
    example.com/service-discovery: artistweb
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - java
  links:
    - url: https://github.com/nitinraj18/my-my-plugin-component/blob/main/catalog-info.yaml
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: test-repo
  system: public-websites
